# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os

class Ui_MainWindow(object):
    def resource_path(self,relative_path):
    #"""Получить абсолютный путь к ресурсу, работает для разработки и PyInstaller"""
        try:
        # PyInstaller создает временную папку и сохраняет путь в _MEIPASS
            base_path = sys._MEIPASS
        except Exception:
        # Если это не PyInstaller, используем текущую папку
            base_path = os.path.abspath(".")
        return os.path.join(base_path, relative_path)
    
    def setmyIcon(self, MainWindow):
        icon_path = self.resource_path("logo.png")
        MainWindow.setWindowIcon(QtGui.QIcon(icon_path))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1600)
        MainWindow.setBaseSize(QtCore.QSize(2000, 800))
        #self.setmyIcon(MainWindow)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1980, 400))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_loadfile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_loadfile.setGeometry(QtCore.QRect(10, 450, 330, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_loadfile.setFont(font)
        self.btn_loadfile.setObjectName("btn_loadfile")
        self.btn_testgen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_testgen.setGeometry(QtCore.QRect(630, 1280, 330, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_testgen.setFont(font)
        self.btn_testgen.setObjectName("btn_testgen")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(510, 560, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 580, 481, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 680, 471, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(510, 660, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.groupBox_col = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_col.setGeometry(QtCore.QRect(10, 820, 300, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_col.setFont(font)
        self.groupBox_col.setObjectName("groupBox_col")
        self.radioButton_1col = QtWidgets.QRadioButton(self.groupBox_col)
        self.radioButton_1col.setGeometry(QtCore.QRect(20, 40, 250, 30))
        self.radioButton_1col.setObjectName("radioButton_1col")
        self.radioButton_1col.setChecked(True)
        self.radioButton_2col = QtWidgets.QRadioButton(self.groupBox_col)
        self.radioButton_2col.setGeometry(QtCore.QRect(20, 100, 250, 30))
        self.radioButton_2col.setObjectName("radioButton_2col")
        self.headergroup = QtWidgets.QGroupBox(self.centralwidget)
        self.headergroup.setGeometry(QtCore.QRect(630, 470, 931, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.headergroup.setFont(font)
        self.headergroup.setCheckable(True)
        self.headergroup.setChecked(False)
        self.headergroup.setObjectName("headergroup")
        self.textBrowser = QtWidgets.QTextBrowser(self.headergroup)
        self.textBrowser.setGeometry(QtCore.QRect(10, 130, 911, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.btn_loadheader = QtWidgets.QPushButton(self.headergroup)
        self.btn_loadheader.setGeometry(QtCore.QRect(240, 30, 300, 75))
        self.btn_loadheader.setObjectName("btn_loadheader")
        self.footergroup = QtWidgets.QGroupBox(self.centralwidget)
        self.footergroup.setGeometry(QtCore.QRect(630, 840, 921, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.footergroup.setFont(font)
        self.footergroup.setCheckable(True)
        self.footergroup.setChecked(False)
        self.footergroup.setObjectName("footergroup")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.footergroup)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 100, 901, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.btn_loadfooter = QtWidgets.QPushButton(self.footergroup)
        self.btn_loadfooter.setGeometry(QtCore.QRect(330, 10, 300, 75))
        self.btn_loadfooter.setObjectName("btn_loadfooter")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 980, 600, 500))
        self.scrollArea.setMaximumSize(QtCore.QSize(600, 500))
        self.scrollArea.setBaseSize(QtCore.QSize(600, 340))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 584, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.themesgroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.themesgroupBox.setGeometry(QtCore.QRect(0, 0, 580, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themesgroupBox.sizePolicy().hasHeightForWidth())
        self.themesgroupBox.setSizePolicy(sizePolicy)
        self.themesgroupBox.setMaximumSize(QtCore.QSize(580, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.themesgroupBox.setFont(font)
        self.themesgroupBox.setCheckable(True)
        self.themesgroupBox.setChecked(False)
        self.themesgroupBox.setObjectName("themesgroupBox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.update_list = QtWidgets.QPushButton(self.centralwidget)
        self.update_list.setGeometry(QtCore.QRect(10, 1490, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_list.setFont(font)
        self.update_list.setObjectName("update_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_load_file = QtWidgets.QAction(MainWindow)
        self.action_load_file.setObjectName("action_load_file")
        self.action_testgen = QtWidgets.QAction(MainWindow)
        self.action_testgen.setObjectName("action_testgen")
        self.action_loadheader = QtWidgets.QAction(MainWindow)
        self.action_loadheader.setObjectName("action_loadheader")
        self.action_loadfooter = QtWidgets.QAction(MainWindow)
        self.action_loadfooter.setObjectName("action_loadfooter")
        self.actionload_themes = QtWidgets.QAction(MainWindow)
        self.actionload_themes.setObjectName("actionload_themes")
        self.actionupdate_list = QtWidgets.QAction(MainWindow)
        self.actionupdate_list.setObjectName("actionupdate_list")

        self.retranslateUi(MainWindow)
        self.btn_loadfile.clicked.connect(self.action_load_file.trigger) # type: ignore
        self.btn_testgen.clicked.connect(self.action_testgen.trigger) # type: ignore
        self.btn_loadheader.clicked.connect(self.action_loadheader.trigger) # type: ignore
        self.btn_loadfooter.clicked.connect(self.action_loadfooter.trigger) # type: ignore
        self.themesgroupBox.clicked['bool'].connect(self.actionload_themes.trigger) # type: ignore
        self.update_list.clicked.connect(self.actionupdate_list.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TESTGen2.0"))
        self.btn_loadfile.setText(_translate("MainWindow", "Загрузить из файла"))
        self.btn_testgen.setText(_translate("MainWindow", "Генерить тест"))
        self.label.setText(_translate("MainWindow", "Количество вариантов"))
        self.label_2.setText(_translate("MainWindow", "Количество вопросов"))
        self.groupBox_col.setTitle(_translate("MainWindow", "Количество колонок"))
        self.radioButton_1col.setText(_translate("MainWindow", "1"))
        self.radioButton_2col.setText(_translate("MainWindow", "2"))
        self.headergroup.setTitle(_translate("MainWindow", "Шапка теста"))
        self.btn_loadheader.setText(_translate("MainWindow", "Файл шапки"))
        self.footergroup.setTitle(_translate("MainWindow", "Футер"))
        self.btn_loadfooter.setText(_translate("MainWindow", "Из файла"))
        self.themesgroupBox.setTitle(_translate("MainWindow", "Разбивка по темам"))
        self.update_list.setText(_translate("MainWindow", "Обновить"))
        self.action_load_file.setText(_translate("MainWindow", "load_file"))
        self.action_testgen.setText(_translate("MainWindow", "testgen"))
        self.action_loadheader.setText(_translate("MainWindow", "loadheader"))
        self.action_loadfooter.setText(_translate("MainWindow", "loadfooter"))
        self.actionload_themes.setText(_translate("MainWindow", "load_themes"))
        self.actionupdate_list.setText(_translate("MainWindow", "update_list"))

def resource_path(relative_path):
    #"""Получить абсолютный путь к ресурсу, работает для разработки и PyInstaller"""
        try:
        # PyInstaller создает временную папку и сохраняет путь в _MEIPASS
            base_path = sys._MEIPASS
        except Exception:
        # Если это не PyInstaller, используем текущую папку
            base_path = os.path.abspath(".")
        return os.path.join(base_path, relative_path)

if __name__ == "__main__":
    
   
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    #icon_path = resource_path("logo.png")
    #MainWindow.setWindowIcon(QtGui.QIcon(icon_path))
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    #ui.setIcon(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

